# Generated by Django 3.2.1 on 2021-05-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210530_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
