# Generated by Django 3.2.1 on 2021-05-30 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_property_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='customer',
        ),
    ]
