# Generated by Django 3.2.1 on 2021-05-31 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_plan_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='auth_token',
        ),
    ]
