# Generated by Django 3.2.1 on 2021-05-31 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_plan_auth_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='checked',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
