# Generated by Django 3.2.1 on 2021-05-31 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customer_gender'),
        ('core', '0013_alter_logo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.customer'),
        ),
    ]
