# Generated by Django 3.2.1 on 2021-06-01 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customer_gender'),
        ('core', '0014_bankaccount_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='checked',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='user',
        ),
        migrations.CreateModel(
            name='EnquiryPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked', models.BooleanField(default=False)),
                ('bank_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bankaccount')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.plan')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
            ],
        ),
    ]
