# Generated by Django 3.2.1 on 2021-06-01 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210601_0227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiryplan',
            old_name='bank_name',
            new_name='bank',
        ),
    ]
