# Generated by Django 3.2.1 on 2021-06-01 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customer_gender'),
        ('core', '0016_rename_bank_name_enquiryplan_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiryplan',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.bankaccount'),
        ),
        migrations.AlterField(
            model_name='enquiryplan',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.plan'),
        ),
        migrations.AlterField(
            model_name='enquiryplan',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customer'),
        ),
    ]
