# Generated by Django 3.2.1 on 2021-06-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210601_0321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiryplan',
            name='bank',
        ),
        migrations.AddField(
            model_name='enquiryplan',
            name='account',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enquiryplan',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='BankAccount',
        ),
    ]
