# Generated by Django 3.2.1 on 2021-06-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_customer_image'),
        ('core', '0018_auto_20210601_0615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiryplan',
            name='user',
        ),
        migrations.AddField(
            model_name='enquiryplan',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.Customer'),
        ),
    ]
