# Generated by Django 3.2.1 on 2021-06-03 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_customer_image'),
        ('core', '0019_auto_20210603_0816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiryplan',
            name='user',
        ),
        migrations.AddField(
            model_name='enquiryplan',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customer'),
        ),
    ]
