# Generated by Django 3.2.1 on 2021-06-15 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='p_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.type'),
        ),
    ]
