# Generated by Django 3.2.1 on 2021-06-16 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_property_p_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='catogory',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='property',
            name='p_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.type'),
        ),
    ]
