# Generated by Django 3.2.1 on 2021-06-19 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_customer_stripe_customer_id'),
        ('core', '0027_alter_property_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customer'),
        ),
    ]
