# Generated by Django 3.1.2 on 2021-06-23 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20210622_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.ForeignKey(default='Select Category', on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
    ]
