# Generated by Django 3.1.2 on 2021-06-27 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20210623_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
