# Generated by Django 3.1.2 on 2021-06-28 06:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_property_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
