# Generated by Django 3.1.2 on 2021-07-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_property_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
