# Generated by Django 3.1.2 on 2021-07-08 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20210706_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='p_type',
            new_name='ptype',
        ),
    ]
