# Generated by Django 3.1.2 on 2021-07-15 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20210708_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='score',
        ),
    ]
