# Generated by Django 3.2 on 2021-05-27 05:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20210527_0517'),
        ('accounts', '0002_auto_20210527_0517'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Customer',
        ),
    ]
