# Generated by Django 3.2.1 on 2021-05-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_profile_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(default='default.png', upload_to='images'),
        ),
    ]
